require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.autopairs"
require "user.nvim-tree"
require "user.keymappings"
require('bufferline').setup()
require "user.lualine"
require "user.autocmd"
